spring:
  application:
    name: tasktracker
  datasource:
    url: jdbc:postgresql://localhost/test?currentSchema=task_tracker
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml